plex:
  restart: always
  image: linuxserver/sonarr
  container_name: sonarr
  volumes:
    - "/dev/rtc:/dev/rtc:ro"
    - "/home/sonarr/config:/config"
    - "/home/sonarr/tv:/tv"
    - "/home/nzbget/downloads:/downloads"
  environment:
    - "PUID=0"
    - "PGID=0"
  ports:
    - 8989:8989  
