plex:
  restart: always
  image: linuxserver/couchpotato
  container_name: couchpotato
  volumes:
    - "/home/couchpotato/config:/config"
    - "/home/media/Movies:/movies"
    - "/home/nzbget/downloads/completed/Movies:/downloads"
  environment:
    - "TZ=EST"
    - "PGID=0"
    - "PUID=0"
  ports:
    - 5050:5050  
