couchpotato:
  restart: always
  image: linuxserver/couchpotato
  container_name: couchpotato
  volumes:
    - "/price/media/couchpotato/config:/config"
    - "/price/media/movies:/movies"
    - "/price/media/downloads:/downloads"
  environment:
    - "TZ=EST"
    - "PGID=0"
    - "PUID=0"
  ports:
    - 5050:5050  
