nzbget:
  restart: always
  image: linuxserver/nzbget
  container_name: nzbget
  volumes:
    - "/price/media/nzbget/config:/config"
    - "/price/media/downloads:/downloads"
  environment:
    - "PUID=0"
    - "PGID=0"
    - "TZ=EST"
  ports:
    - 6789:6789  
